call rasm\load_ams.bat
call rasm\load_col.bat
call rasm\load_cpm.bat
call rasm\load_ent.bat
call rasm\load_fos.bat
call rasm\load_mxb.bat
call rasm\load_mxd.bat
call rasm\load_wbw.bat
call rasm\load_s3k.bat
call rasm\load_t80.bat
call rasm\load_vz3.bat
call rasm\load_tat.bat
call rasm\load_s16.bat
call rasm\load_sp.bat
call rasm\load_sp2.bat
call rasm\load_sp3.bat
call rasm\load_sym.bat

call rasm\ams_64.bat
call rasm\ams_256.bat
call rasm\ams_256s.bat
call rasm\ams_512.bat
call rasm\ams_1024.bat
call rasm\ams_2048.bat
call rasm\ams_4096.bat
call rasm\ams_v64.bat
call rasm\mem_none.bat

call rasm\bios_ams.bat
call rasm\bios_col.bat
call rasm\bios_cpm.bat
call rasm\bios_ent.bat
call rasm\bios_fos.bat
call rasm\bios_mxb.bat
call rasm\bios_mxd.bat
call rasm\bios_wbw.bat
call rasm\bios_s3k.bat
call rasm\bios_t80.bat
call rasm\bios_vz3.bat
call rasm\bios_tat.bat
call rasm\bios_s16.bat
call rasm\bios_sp.bat
call rasm\bios_sp2.bat
call rasm\bios_sp3.bat
call rasm\bios_sym.bat

call rasm\kernel.bat
call rasm\shell.bat

